name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Other changes'
    labels:
      - 'dependencies'
      - 'documentation'

exclude-labels:
  - "skip-changelog"
  - "maintenance"
  - "trivial"

version-resolver:
  major:
    labels:
      - 'major version'
  minor:
    labels:
      - 'minor version'
  patch:
    labels:
      - 'patch version'
  default: patch

template: |
  ## What’s Changed

  $CHANGES
