sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

git:
  autocrlf: input

os:
  - linux
  - windows
  - osx

before_install:
  - npm i -g npm@7
  - travis_retry npm install

script:
  - npm test
